name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js (match your package.json “>=8.0.0”; using 18.x for performance & security)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install dependencies cleanly
      - name: Install dependencies
        run: npm ci

      # 4. Build your Three.js app
      - name: Build
        run: npm run build

      # 5. Configure GitHub Pages (official Pages action)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 6. Upload the build output to Pages
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/

      # 7. Publish to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
